CLS
PRINT "WELCOME TO THE HYPER STUDIO STACK PLAYER"
INPUT "WOULD YOU LIKE TO SEE THE DEMO (1) OR OPEN YOUR OWN (2) >", c
IF c = 1 THEN GOTO DEMO
IF c = 2 THEN GOTO OPENER
DEMO:
SHELL "C:\HSPLAYER\HSPLAYER.EXE C:\HSPLAYER\MONKEYS.STK"
END
OPENER:
PRINT "PLEASE TYPE THE LOCATION AND THE STACK ON YOUR COMPUTER"
PRINT "EXAMPLE:  c:\hsplayer\foldername\yourstack.stk (STACKNAME [yourstack.stk] MUST"
PRINT "BE NO MORE THAN 8 CHARACTERS LONG [SAME WITH FOLDER NAME(hsplayer\"
PRINT "OR foldername\)])"
INPUT ">", inper$
SHELL "C:\HSPLAYER\HSPLAYER.EXE " + inper$
END

