SHELL "CD >TMPDIR.TMP"
SHELL "PATH >TMPPTH.TMP"
OPEN "TMPDIR.TMP" FOR INPUT AS #1
OPEN "TMPPTH.TMP" FOR INPUT AS #2
INPUT #1, DIR$
INPUT #2, PATH$
CLOSE #1
CLOSE #2
SHELL "DEL TMPDIR.TMP"
SHELL "DEL TMPPTH.TMP"

