CLS
SCREEN 7
COLOR 10
PRINT "YOU NEED A PASSWORD FOR THIS APLICATION"
COLOR 12
INPUT "TYPE IT HERE >", choice$
IF choice$ = "CL8-482-MB12" THEN GOTO ln
IF choice$ = "JohnTOlds@Aol.com 1986 947-9941" THEN GOTO ln
IF choice$ = "SAM" THEN GOTO ln
IF choice$ = "DAD/MOM" THEN GOTO ln
COLOR 10
PRINT "YOU ANSWERED WRONG"
COLOR 12
PRINT "YOU WILL NOW BE JAMED IN A LOOP"
FOR i = 1 TO 100000
start:
COLOR 10
PRINT "LOOP LOOP LOOP"
COLOR 12
PRINT "LOOP LOOP LOOP"
GOTO start
ln:
SHELL "start c:\jt\qbasic.exe"
END


