CLS
cl:
PRINT
PRINT "This is SAM's Language 1.0"
PRINT
PRINT "SAM'S ALPHABET"
PRINT
PRINT "crsnyrufurkkSAMOLDStguzkkJT"
PRINT
PRINT "SAM'S NUMBERS"
PRINT
PRINT "1009875654321208695046123442"
PRINT
INPUT "DO YOU WANT TO SEE SAM'S LANGUAGE AGAIN? (1=TRY AGAIN. 2=QUIT) >", choice
IF choice = 1 THEN GOTO cl
IF choice = 2 THEN GOTO qt
qt:
PRINT
PRINT "THANK YOU FOR TRYING SAM'S LANGUAGE  v. 1.0 "
END

